apiVersion: 1
datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    basicAuth: false
    isDefault: true
    jsonData:
      version: Flux
      organization: myorg
    secureJsonData:
      token: mysupersecrettoken123

