# Use the official InfluxDB 2.x image as a base
FROM influxdb:2.7

# Set working directory
WORKDIR /docker-entrypoint-initdb.d

# (Optional) Copy initialization scripts or sample data
# COPY init_script.sh /docker-entrypoint-initdb.d/
# COPY seed-data.lp /docker-entrypoint-initdb.d/

# Expose the InfluxDB port
EXPOSE 8086

# Default command
CMD ["influxd"]

